### ISSUE TITLE
Previous Aion version compatibility

### ISSUE THREAD

**Issue by tarasevich-dmitry** [EL-P-3000/OpenAIONDPS#2]
Hi, is it possible to use with earlier Aion versions? 
I want to thy it with Aion v3.0 
Also is it possible to add English documentation? I can help with it 
Thanks

**Comment by EL-P-3000** [comment]
このプロジェクトは日本語のみとなります。
また、以前のバージョンのAIONは対象外ですし、今後もサポートはしません。
